import {ColorValue} from 'react-native';

export type TColorNames =
  | 'BASE_BLACK'
  | 'BASE_PRIMARY'
  | 'BASE_DARK_BRAND'
  | 'BASE_WHITE'
  | 'BASE_GREY'
  | 'BASE_STORM_GREY'
  | 'BASE_LIGHT_GREY'
  | 'BASE_LIGHT_GREY2'
  | 'BASE_GREY1'
  | 'BASE_GREY2'
  | 'BASE_GREEN'
  | 'BASE_DEEP_GREEN'
  | 'BASE_DEEP_GREEN2'
  | 'BASE_GREEN2'
  | 'BASE_TEAL'
  | 'BASE_BRIGHT_TEAL'
  | 'BASE_LIGHT_TEAL'
  | 'BASE_SOFT_PURPLE'
  | 'BASE_DARK_PURPLE'
  | 'BASE_BLUE'
  | 'BASE_BLUE2'
  | 'BASE_LILAC'
  | 'BASE_BRIGHT_LILAC'
  | 'BASE_RED'
  | 'BASE_RED2'
  | 'BASE_RED_ERROR'
  | 'BASE_ORANGE'
  | 'OPACITY_WHITE'
  | 'OPACITY_WHITE2'
  | 'transparent'
  | 'BASE_BROWN'
  | 'BASE_BROWN_LIGHT'
  | 'BASE_ORANGE_LIGHT'
  | 'BASE_YELLOW_LIGHT';

export interface TBaseThemeColors extends Record<TColorNames, ColorValue> {}
